EventManager/EventManager/Controllers/ElectionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManager.Controllers
{
    public class ElectionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EventManager/EventManager/Controllers/SignalRController.cs
using EventManager.Entitys;
using EventManager.Models;
using EventManager.SignalR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace EventManager.Controllers
{
    public class SignalRController : Controller
    {
        private readonly NotifEntities context;

        public SignalRController(NotifEntities context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public HttpResponseMessage SendNotification([FromBody]NotifModels obj)
        {
            NotificationHub objNotifHub = new NotificationHub(context);
            Notification objNotif = new Notification();
            objNotif.Id = 1;
            objNotif.SentTo = obj.UserID;

            //context.Configuration.ProxyCreationEnabled = false;
            context.Notifications.Add(objNotif);
            context.SaveChanges();

            objNotifHub.SendNotification(objNotif.SentTo);

            var query = (from t in context.Notifications
                         select t).ToList();


            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}

EventManager/EventManager/Controllers/WheelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManager.Controllers
{
    public class WheelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EventManager/EventManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EventManager</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script> *@

    <link rel="stylesheet" href="~/css/vendor.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Site.css" />
    <script src="~/js/vendor.js" asp-append-version="true"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.1/dist/sweetalert2.all.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.1/dist/sweetalert2.min.css">
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">EventManager</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                <li class="nav-item"><a asp-controller="Wheel" asp-action="Index" class="nav-link">Wheel</a></li>
                <li class="nav-item"><a asp-controller="Election" asp-action="Index" class="nav-link">Votes</a></li>
                <li class="nav-item"><a asp-controller="SignalR" asp-action="Index" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>

</html>